id: P003222
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 10:48:28.367281
source_metadata:
  id: bdr:W1KG25782
  title: ཚད་མ་རིག་པའི་སྤྱི་བཤད།
  author: ''
  volumes:
    02293ea54dda4e6e8720c0641d48d879:
      image_group_id: I1KG25784
      title: ''
      volume_number: 1
      total_pages: 248
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
