id: IF90B702F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T16:57:48+00:00'
last_modified: '2022-06-07T18:29:05.394141+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25782
  title: ཚད་མ་རིག་པའི་སྤྱི་བཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    773F:
      image_group_id: I1KG25784
      title: ''
      total_pages: 248
      order: 1
      base_file: 773F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
